<Project>
  <PropertyGroup>
    <Version>5.0.3</Version>
    <Company>Zack Loveless</Company>
    <Copyright>© Copyright 2025 Zack Loveless.</Copyright>
    <Authors>Zack Loveless</Authors>
    <PackageProjectUrl>https://github.com/zloveless/Atlantis/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/zloveless/Atlantis/</RepositoryUrl>
    <OutputPath>$(SolutionDir)Build\$(Configuration)\</OutputPath>
  </PropertyGroup>
</Project>
