<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Product>Atlantis</Product>
    <Description>Atlantis is a collection of code that is common amongst many pet projects.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
  </ItemGroup>
</Project>
