name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version (e.g. 1.2.3)'
        required: true

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          source-url: "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        env:
          NUGET_AUTH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Pack
        run: dotnet pack -c Release --no-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nupkg-artifacts
          path: |
            Build/Release/**/*.nupkg
            !Build/Release/**/*.snupkg
      
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          generate_release_notes: true
          files: |
            Build/Release/**/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish nuget packages to GitHub
        run: dotnet nuget push Build/Release/*.nupkg
